### ISSUE TITLE
Missing descriptions

### ISSUE THREAD

**Issue by hmaskat17** [ec2u/data#28]
**Steps to reproduce**
1. Make a request to https://data.ec2u.eu/events/ endpoints
2. Check the description property.

**What did you expect to happen?**
Descriptions have their full text included.

**What did actually happen?**
Descriptions are very short and do not reflect the source. They also end in "...".

**Would you share any observation or additional context about the bug?**
Example of missing descriptions:

Jena > Space Tour
- Missing in MMT - https://app.mymobiletutor.eu/en/jena/events/06c1a388-7a1f-4155-941e-f015fc0be5c4
- Missing from API - https://data.ec2u.eu/events/5ab607ba689d8ad3e0f3662846a3f8f5
- Full description in UI - https://data.ec2u.eu/events/5ab607ba689d8ad3e0f3662846a3f8f5

Missing descriptions from Turku, Jena, Poitiers...

@ec2u/mmt

**Comment by knoan** [comment]
JSON event description fields slightly deviate from `schema.org` property names to handle a clash with the Dublin Core vocabulary, in use under the hood to manage generic resource metadata:

|detail level|graph property|JSON field|
|---|---|---|
|short description|`dct:description`|`description`|
|short description|`schema:disambiguatingDescription `|`disambiguatingDescription`|
|extended description|`schema:description`|`fullDescription`|

Unless explicitly provided by the source, short descriptions are generated by clipping extended ones and adding trailing '…' as required; extended descriptions may be safely rendered as Markdown as demonstrated in the details view of the search UI.

Takeaway: 

- use `disambiguatingDescription` to render compact event previews
- use `fullDescription` to render detailed views, possibly taking advantage of Markdown 

Will update the docs to avoid further confusion.
