### ISSUE TITLE
Missing paragraphs (new lines) in descriptions

### ISSUE THREAD

**Issue by hmaskat17** [ec2u/data#29]
**Steps to reproduce**
1. Check event description fields (e.g. fullDescription) the API returns or
2. Check event descriptions from MMT app or EC2U interface

**What did you expect to happen?**
Descriptions are formatted with paragraphs i.e. in this case, new lines `\n`

**What did actually happen?**
No paragraphs

**Would you share any observation or additional context about the bug?**
*Example:*
Pentti Koivikko (https://kalenteri.turku.fi/events/node/993197)
- Paragraphs missing from EC2U interface (https://data.ec2u.eu/events/1fbcdcbd4718be856b6c30e095e32d82) and MMT app
- Paragraphs are included in the source > https://linkedevents-api.turku.fi/v1/event/turku:993197/

*Another example:*
Mamsellimyllyssä kummittelee (https://kalenteri.turku.fi/events/node/990401)
- Paragraphs missing from MMT app
- Paragraphs are included in the source > https://linkedevents-api.turku.fi/v1/event/turku:990401/
- This particular event is missing from Knowledge Hub but has been imported to MMT with external ID `/events/73f3b480f4b087700481c1f52f220e1d`

**Proposal:**
- Include all paragraph formatting in events description fields.
- Why is event Mamsellimyllyssä kummittelee `/events/73f3b480f4b087700481c1f52f220e1d` missing?

@ec2u/mmt

**Comment by knoan** [comment]
Fixed for future events crawled from Turku City under the assumptions that descriptions don't contains HTML markup.

Please report as a new dedicated issue if relevant also for other sources.
