### ISSUE TITLE
Missing previously available data in API

### ISSUE THREAD

**Issue by hmaskat17** [ec2u/data#44]
We are having the following issues with the API:

**API returns all events even when using updated filter**

For example making requests to `https://data.ec2u.eu/events/?@=0&%23=100&updated>=2024-10-13T00:00:00.000Z` returns all events when it should return only events after 13th of October.

**API returns missing properties previously available**

For example, events are missing the properties:
- university
- publisher
- modified
etc..

At minimum the `university` and `publisher` properties are a critical field that we have required on our end. Are these still available?

**API returns missing location data for events before API changes**

For example, `https://data.ec2u.eu/events/46dcd8332851dc7626e6e33036cf56fe` has missing location data in the new API when it previously had some address data.

**Comment by knoan** [comment]
> **API returns all events even when using updated filter**
> For example making requests to https://data.ec2u.eu/events/?@=0&%23=100&updated>=2024-10-13T00:00:00.000Z returns all events when it should return only events after 13th of October.

After reviewing updating timestamps, we opted for removing them from the data model: almost all sources aren't able to provide them reliably and keeping track of the changes on the server side proved absolutely impractical.

The best you can do is to retrieve all future event paginating as required as:

```https://data.ec2u.eu/events/?@=0&#=100&startDate>=2024-10-13T00:00:00.000Z```

**Comment by knoan** [comment]
> **API returns missing properties previously available**



* university and publisher now available for all events
* all creation/updating timestamps where removed for the above-mentioned reasons
* other properties may be missing from the update data model: please review current contents @ https://data.ec2u.eu/datasets/events

**Comment by knoan** [comment]
> API returns missing location data for events before API changes

Most location data appear to be missing because of changes in the underlying data sources: back to you as soon as we complete a revision of the ingestion pipelines

**Comment by knoan** [comment]
> **API returns missing properties previously available**

Data for Pavia/City already update in production to support integration testing, e.g.: https://data.ec2u.eu/events/46dcd8332851dc7626e6e33036cf56fe

**Comment by hmaskat17** [comment]
We still require the type of publisher (university or city). This was in the `publisher.coverage` property in the previous api version as the value `/terms/City` etc. Can this be added to the new version? Otherwise we would have to map the publisher id's to the type but this will require updating the list for every newly integrated university. Was there a endpoint to get all the publisher ids? @knoan

**Comment by knoan** [comment]
Event publisher and organisers were remodelled as `schema:Organization` entities as per https://data.ec2u.eu/datasets/events. The relevant information is now available as `publisher.about`, which is now included by default in the data model (see sample below).

Note that organisations could be associated with multiple `about` concepts: you need to scan the JSON array looking for concepts in the `/concepts/organizations/` IRI space. Available values are listed @ https://data.ec2u.eu/concepts/organizations.


```json
{
      "id": "/events/09a78e0f05b174c88cf402672dca6842",
      "url": [
        "http://www.kanneltalo.fi/fi/tapahtumat/event/CD8426417E51AAA7506E7762FDE66545/Kino_Kuutamo_Mummola_7_"
      ],
      "name": {
        "fi": "Kino Kuutamo: Mummola (7) – Maksuttomat maanantait",
        "en": "Kino Kuutamo: Mummola (7) – Free Mondays"
      },

     ⋮

      "university": "/universities/turku",
      "startDate": "2024-12-09T15:00:00.0Z",
      "isAccessibleForFree": true,
      "publisher": {
        "id": "https://kalenteri.turku.fi/",
        "name": {
          "fi": "Turun kaupunki / Tapahtumakalenteri",
          "en": "City of Turku / Event's Calendar"
        },
        "about": [
          {
            "id": "/concepts/organizations/city",
            "label": {
              "en": "City"
            }
          }
        ]
      }
    }
```
